probe_interval: 30
iperf3_interval: 300
ping_count: 10
iperf3_duration: 5
iperf3_port: 5201
thresholds:
  ping_warn_ms: 100
  ping_crit_ms: 300
  loss_warn_pct: 1
  loss_crit_pct: 5
  tcp_warn_ms: 150
  tcp_crit_ms: 500
  bw_warn_mbps: 50
  bw_crit_mbps: 10
hosts:
- name: google
  host: 35.234.22.51
  ssh_user: darwin
  ssh_port: 22
  iperf3: true
- name: nube
  host: 64.118.147.86
  ssh_user: root
  ssh_port: 22
  iperf3: true
  password: REDACTED
- name: nube-1
  host: 64.118.149.162
  ssh_user: root
  ssh_port: 22
  iperf3: true
  password: REDACTED
- name: v1
  host: 64.176.61.229
  ssh_user: root
  ssh_port: 22
- name: v2
  host: 158.247.227.13
  ssh_user: root
  ssh_port: 22
  password: REDACTED
